// Place helpers used by Manage Atlas: labels, matching/reuse, and id slugs.
// Place reuse keeps the domain honest — one geographic Place can be referenced
// by several Visits and a Wishlist without creating duplicates (PRODUCT_SPEC
// §5, §26).
import type { GeocodingResult } from "./geocode";
import type { Place, PlaceType } from "./types";

export const PLACE_TYPE_LABELS: Record<PlaceType, string> = {
  city: "City",
  region: "Region",
  island: "Island",
  natural_area: "Natural area",
};

export const PLACE_TYPES: PlaceType[] = ["city", "region", "island", "natural_area"];

export function placeTypeLabel(t: PlaceType | undefined): string {
  return t ? (PLACE_TYPE_LABELS[t] ?? t) : "—";
}

// normalize compares names loosely so "Jülich / Aachen" vs "Jülich" don't
// accidentally collapse, but "Amsterdam" vs "amsterdam " do.
function normalizeName(s: string): string {
  return s.trim().replace(/\s+/g, " ").toLowerCase();
}

// findMatchingPlace returns an existing Place that the geocoding result refers
// to, or null when a new Place should be created. Matching is conservative:
// exact name + country code, then proximity (within ~2 km) with the same
// country. Reusing avoids duplicate Place records across Visits/Wishlist.
export function findMatchingPlace(
  places: Place[],
  result: Pick<GeocodingResult, "name" | "countryCode" | "coordinates">
): Place | null {
  const name = normalizeName(result.name);
  const cc = (result.countryCode ?? "").toUpperCase();
  for (const p of places) {
    if (p.countryCode.toUpperCase() !== cc) continue;
    if (normalizeName(p.name) === name) return p;
  }
  const lat = result.coordinates.lat;
  const lng = result.coordinates.lng;
  for (const p of places) {
    if (p.countryCode.toUpperCase() !== cc) continue;
    const dLat = (p.coordinates.lat - lat) * 111.0;
    const dLng = (p.coordinates.lng - lng) * 111.0 * Math.cos((lat * Math.PI) / 180);
    if (dLat * dLat + dLng * dLng <= 2 * 2) return p; // ~2 km radius
  }
  return null;
}

// newPlaceFromResult turns a normalized geocoding result into a draft Place.
// The id is generated by the runtime on creation; the draft only carries the
// display data.
export function newPlaceFromResult(
  result: Pick<GeocodingResult, "name" | "country" | "countryCode" | "suggestedType" | "coordinates">,
  type: PlaceType
): Omit<Place, "id"> {
  return {
    name: result.name,
    country: result.country ?? "",
    countryCode: result.countryCode ?? "",
    type,
    coordinates: { lat: result.coordinates.lat, lng: result.coordinates.lng },
  };
}

export function slugify(s: string): string {
  return s
    .toLowerCase()
    .replace(/[^a-z0-9]+/g, "-")
    .replace(/^-+|-+$/g, "");
}

// distanceKm between two coordinates (haversine, km).
export function distanceKm(
  a: { lat: number; lng: number },
  b: { lat: number; lng: number }
): number {
  const R = 6371;
  const dLat = ((b.lat - a.lat) * Math.PI) / 180;
  const dLng = ((b.lng - a.lng) * Math.PI) / 180;
  const s =
    Math.sin(dLat / 2) ** 2 +
    Math.cos((a.lat * Math.PI) / 180) * Math.cos((b.lat * Math.PI) / 180) * Math.sin(dLng / 2) ** 2;
  return 2 * R * Math.asin(Math.sqrt(s));
}
